### ISSUE TITLE
Array indexed exception for LongestCommonPrefix.java

### ISSUE THREAD

**Issue by Akhilj786** [blakeembrey/code-problems#158]
The assumption made while coding is: 1st string will be smallest but i believe that wont be the case.
So we need to find the smallest string(in terms of length).
I have done something similar here:
https://github.com/Akhilj786/Algorithms/blob/master/src/DynamicProgram/LongestCommonPrefix.java#L11-L17

**Comment by blakeembrey** [comment]
You're absolutely right and this is probably a bug. You're welcome to submit a patch :+1:

**Comment by blakeembrey** [comment]
Actually, isn't this condition handling it? https://github.com/blakeembrey/code-problems/blob/master/solutions/java/LongestCommonPrefix.java#L13

**Comment by Akhilj786** [comment]
:+1:
