### ISSUE TITLE
largest-palindrome.js break the test in JsHint phase.

### ISSUE THREAD

**Issue by caoglish** [blakeembrey/code-problems#175]
I run the ```npm test```

The error message is following:

solutions\javascript\largest-palindrome.js: line 2, col 3, 'const' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 2, col 41, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 4, col 8, 'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 6, col 19, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 10, col 14, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 14, col 3, 'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 14, col 19, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 16, col 8, 'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 17, col 5, 'let' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 17, col 25, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 20, col 7, 'const' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
solutions\javascript\largest-palindrome.js: line 20, col 48, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 23, col 28, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 28, col 17, Missing semicolon.
solutions\javascript\largest-palindrome.js: line 29, col 2, Missing semicolon.

it seems that largest-palindrome.js use ES6 syntax and jshint did not support ES6 syntax by default.

**Comment by blakeembrey** [comment]
Thanks, I'm going to disable linting for now.
